
model_config:
  model_name: efficientnet_b0  
  backbone_unfreeze_last_layers_num: 0    

artifacts_config:
  artifacts_root: artifacts

  data_ingestion:
    root_dir: artifacts/data_ingestion
    source_URL: kaggle://pythonafroz/solar-panel-images
    local_data_file: artifacts/data_ingestion/solar-panel-images.zip
    unzip_dir: artifacts/data_ingestion/solar_panel_images

  prepare_base_model:
    root_dir: artifacts/prepare_base_model
    base_model_path: artifacts/prepare_base_model/base_model.keras
    updated_base_model_path: artifacts/prepare_base_model/base_model_updated.keras


  prepare_callbacks:
    root_dir: artifacts/prepare_callbacks
    checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.keras

  training:
    root_dir: artifacts/training
    trained_model_path: artifacts/training/model.keras

  evaluation:
    root_dir: artifacts/evaluation
    report_json: artifacts/evaluation/report.json
