augmentation: true
batch_size: 32
num_epochs: 1
shuffle: true
val_split: 0.20     
seed: 42
mixed_precision: auto    # "auto" | "fp16" | "off"

loss:
  name: sparse_categorical_crossentropy
metrics:
- sparse_categorical_accuracy
optimizer:
  name: adamw           # "adam" | "adamw" | "sgd"
  lr: 0.0001           
  weight_decay: 0.0001   # AdamW only 
  beta_1: 0.9            # Adam/AdamW
  beta_2: 0.999          # Adam/AdamW
  epsilon: 1e-7          # Adam/AdamW
  momentum: 0.9          # SGD only
  nesterov: true         # SGD only
  clipnorm: 1.0          # works for all
  clipvalue:             # works for all (optional)




